### ISSUE TITLE
Please use actual value

### ISSUE THREAD

**Issue by effaamponsah** [TutorialG12/java_project#2]
https://github.com/TutorialG12/java_project/blob/4c04f07c52caf701971b80163227fc86ec448b98/Tests/com/company/LectureTest.java#L18

I think you should put the actual value here instead 😅. Or is there something i am missing out on this?

**Comment by AlbertPrince** [comment]
Yeah thanks for the advice. We will change it later on

**Comment by AlbertPrince** [comment]
Yeah thanks for the advice. We will change it later on
