### ISSUE TITLE
Use of variables

### ISSUE THREAD

**Issue by effaamponsah** [TutorialG12/java_project#3]
https://github.com/TutorialG12/java_project/blob/4c04f07c52caf701971b80163227fc86ec448b98/src/com/company/Student.java#L20-L22

Can the above be changed to something below
```java
 for (double grade : this.grades) { 
    total += grade; 
 } 
```
Using the (item) is more preferable than using `i`'s. I see you doing the correct thing at other places. What happened here? 😭😭

**Comment by AlbertPrince** [comment]
sure we'll do that right away

**Comment by AlbertPrince** [comment]
sorted
